name: youtube_$(Date:yyyymmdd)$(Rev:.r)
trigger:
 - main
pool:
  name: Azure Pipelines
steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'youtube-clone-azure-resource-manager-service-connection'
    appType: 'webAppLinux'
    WebAppName: 'youtube-cloneo1'
    packageForLinux: '$(System.DefaultWorkingDirectory)/build'
    RuntimeStack: 'STATICSITE|1.0'